
// get all customers
GET http://localhost:3000/customers HTTP/1.1
###

// get customer by id
GET http://localhost:3000/customers/15 HTTP/1.1
###

// get basket of customer by id
GET   http://localhost:3000/customers/15/basket/ HTTP/1.1
# content-type: application/json
###

// add item to basket of customer by id
PUT  http://localhost:3000/customers/15/basket HTTP/1.1
content-type: application/json

{"itemId":7,"itemQuantity":3}
###

// delete item by id from customer by id
DELETE   http://localhost:3000/customers/15/basket/7 HTTP/1.1
# content-type: application/json
###










//NOT IN FUNCTIONAL REQUIREMENTS? :


// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":15,"customerFistName":"John","customerLastName": "Johnson", "customerBasket":[]}

//tilføj basketID
###

// update all info about customer including basket
PUT  http://localhost:3000/customers/15 HTTP/1.1
content-type: application/json

{"customerId":15,"customerFistName":"John","customerLastName": "Johnson", "customerBasket":[{"itemId":1,"itemQuantity":3},{"itemId":4,"itemQuantity":1}]}

###

// delete customer
DELETE  http://localhost:3000/customers/15 HTTP/1.1

###